<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <ProjectReference Include="../../src/Rrflow.Rrd.Client/Rrflow.Rrd.Client.csproj" />
  </ItemGroup>
</Project>
